# docker-compose.yml

version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GENAIBACKEND: "http://localhost:8000"
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
