# docker-compose.yml

version: "3.9"
services:
  genaipg:
    image: ankane/pgvector:v0.5.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: genaichat
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data_genai_deploy:/var/lib/postgresql/data/
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GENAIBACKEND: "http://localhost:8000"
    working_dir: /app
    ports:
      - "3000:3000"
    image: fastgenai
    env_file:
     - .env
volumes:
  postgres_data_genai_deploy :